[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "json_parser"
version = "0.1"
description = "A Python library that parses JSON from TMDB Source to Graph."
authors = [
    {name = "Nemanja Simsic", email = "nemanjasimsic02@gmail.com"},
]
requires-python = ">=3.6"

dependencies = [
    "api"
]

[project.entry-points."parser"]
file_system_data_source = "JSON_parser.json_parser:JSONParser"
