[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "api"
version = "0.1"
description = "A Python library that contains abstractions that model the API for Data source and Visualizer plugins."
authors = [
    {name = "Nemanja Simsic", email = "nemanjasimsic02@gmail.com"},
]
requires-python = ">=3.6"

dependencies = [
    "requests",
    "python-dotenv"
]

[project.scripts]
data_source_api = "api.tmdb_source_api:DataSourceAPI.fetch_data"
visualizer_api = "api.block_visualizer_api:VisualizerAPI.visualize_data"