[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "api"
version = "0.1"
description = "A Python library that contains abstractions that model the API for Data source and Visualizer plugins."
authors = [
    {name = "Nemanja Simsic", email = "nemanjasimsic02@gmail.com"},
]
requires-python = ">=3.6"

[project.scripts]
data_source_api = "api.data_source_api:main"
visualizer_api = "api.visualizer_api:main"

[project.dependencies]
requests = "^2.25.1"
python-dotenv = "^0.15.0"
abc = "^0.0.1"
typing = "^3.7.4.3"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]