[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "block_visualizer"
version = "0.1"
description = "Block visualizer plugin for Filmoteka"
authors = [
    {name = "Nemanja Simsic", email = "nemanjasimsic02@gmail.com"},
]
requires-python = ">=3.6"

dependencies = [
    "api",
    "django"
]

[project.entry-points."visualiser"]
entry_block_vis = "block_visualizer.block_visualizer:BlockVisualizer"

[tool.setuptools.package-data]
block_visualizer = ["templates/*.html"]