[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "filmoteka_platform"
version = "0.1"
description = "A Python library that provides core functionalities for graph manipulation and facilitates communication between plugins."
authors = [
    {name = "Nemanja Simsic", email = "nemanjasimsic02@gmail.com"},
]
requires-python = ">=3.6"

dependencies = [
    "api"
]

[project.scripts]
plugin_manager = "platform.plugin_manager:PluginManager"